### ISSUE TITLE
Apple Watch App

### ISSUE THREAD

**Issue by fmarcoux96** [IPCams/BugTracker#16]
**Is your feature request related to a problem? Please describe.**
Feature request because I know it's possible.

**Describe the solution you'd like**
Apple Watch app, a simple one with a list of feeds. Apple does it on HomeKit, I can see my cameras linked through Homebridge.

**Additional context**
Could be RTSP (H264) feed or MJPEG. Just mirror the app configs, but also, if possible, allow the use of the app without the phone (I know it can be done, not sure how tho). We could then use the Wi-Fi/LTE on the Watch to see our live feeds.

**Comment by tylerjonesio** [comment]
Thanks for the request! I've got something in the works for this that will hopefully be in the next release.

**Comment by tylerjonesio** [comment]
Great news! IPCams 2.1 is currently in the process of rolling out on the App Store and includes basic Apple Watch support. 

The watch app is a fully independent app where you can add, edit, & manage cameras directly from the watch and functions without a connected iPhone, but also syncs your existing camera data from the iPhone app via iCloud. MJPEG camera streams are supported natively, but unfortunately rtsp streams aren't at the moment due to the lack of a built in way to decode the stream. Since the app lacks native rtsp capabilities it can instead create a pseudo live stream from jpeg snapshots  for those cameras. It's not the best experience, but it works well enough as an alternative on the watch. Hopefully as watchOS evolves I can eventually bring native rtsp support to the app. 

Feel free to leave a bug report for any issues that arise or file a feature request for any improvement suggestions.

**Comment by fmarcoux96** [comment]
I believe there is a way to use H264 decoding on the Watch has HomeKit does it. When I use Homebridge to link my cameras to it, I can see the live feed via my Watch. Unless HomeKit transcodes into something else, but not as far as I could tell.
