### ISSUE TITLE
Wrong  stream displayed on phone rotation 

### ISSUE THREAD

**Issue by nickmay** [IPCams/BugTracker#29]
**Describe the bug**
I have 4 rtsp video streams in a dashboard.When I display the dashboard  in portrait mode I see output from all 4 cameras. When I rotate the iPhone 6s into landscape the output from stream 2 is duplicated in stream 3 thumbnail. So I have 2 stream 2 thumbnails. Touching that second 2-should-be-3 thumbnail brings up the correct stream. 

**To Reproduce**
Set up dashboard with 4 streams on an iPhone 6s. Display dashboard. Make full screen. Rotate phone.

**Expected behavior**
The stream thumbnail should reflect the stream shown when it is clicked.

**Screenshots**
I can send you a video if you wish.

**App Version**
2.1.1 but bug had been present since v1. I am running the Pro version.

**Device & OS Version**
iPhone 6s running latest version of iOS as of today. 

**Additional context**
None

**Comment by nickmay** [comment]
I have just set up another iPhone with these same 4 rtsp cameras and have exactly the same problem. So the issue is more than a one off.

**Comment by scbauer** [comment]
I came here to try to explain the bug I was seeing, but it looks like @nickmay is experiencing the same thing. I’ve reproduced this bug on my iPhone 12 Pro Max (app version 2.1.1), but interestingly it happens multiple ways. I’ve rotated a 4-camera view to landscape and see camera 2 show the camera 3 stream (along with camera 3, so it’s duplicates), then when I go back to portrait (vertical screen), sometimes it still shows 3 streams (with one repeated) and sometimes it actually SWAPS so now camera 2 is seen in the camera 2 slot, but now camera 2 is also shown in the camera 3 slot (whereas in the landscape mode, camera 3 was shown in slot 2 and 3). 

Love the app (so much so that I bought the lifetime premium upgrade), so hopefully this info helps fix the bugs.

**Comment by tylerjonesio** [comment]
Good news! IPCams 2.2 is in the process of rolling out which includes a fix for the rotation issue. Please let me know if you still run into this issue, but hopefully rotation should work properly now.
