### ISSUE TITLE
Back button is missing in cameras view

### ISSUE THREAD

**Issue by longzheng** [IPCams/BugTracker#4]
**Describe the bug**
Viewing a specific camera from the "cameras" view does not show a back button

**To Reproduce**
1. Open app
2. Select "cameras" tab
3. Select a camera
4. No back button in header

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/484912/91646616-647a0880-ea94-11ea-9166-ce274946031c.jpeg)

**App Version**
1.8.1

**Device & OS Version**
iPhone 11 Pro
iOS 14 beta 6

**Additional context**

**Comment by tylerjonesio** [comment]
Thanks for the report! From what I can tell, this is a beta issue with the iOS 14 beta that has cropped up in one of the later releases (beta 5 or 6). This issue was not occurring when the app was previously tested on beta 4. Since I can't target the iOS 14 sdk directly just yet, I'm trying to look into ways I can work around this in the mean time.

**Comment by fmarcoux96** [comment]
> Thanks for the report! From what I can tell, this is a beta issue with the iOS 14 beta that has cropped up in one of the later releases (beta 5 or 6). This issue was not occurring when the app was previously tested on beta 4. Since I can't target the iOS 14 sdk directly just yet, I'm trying to look into ways I can work around this in the mean time.  

I would simply add a back button next to the full screen button.

**Comment by tylerjonesio** [comment]
There is a new release (1.8.2) rolling out now that should fix this issue when running on iOS 14.

**Comment by longzheng** [comment]
Thanks. Confirm fixed.
