### ISSUE TITLE
Live video not visible in landscape mode

### ISSUE THREAD

**Issue by IchSchreiGleich** [IPCams/BugTracker#47]
**Describe the bug**
Switching from portrait to landscape with active connection to a camera results a blank screen and live view disappears.

**To Reproduce**
Switching from portrait to landscape with active connection.

**Expected behavior**
Live video should be visible in landscape view. ;)

**Screenshots**
Maybe later, issue should be easily reproducible.

**App Version**
2.3

**Device & OS Version**
List device (iPhone/iPad), model (XS, 11 Pro, etc.) and OS version (13.5, 14.0, etc.).
iPhone, 8 Plus (iOS 14.4.2)

**Additional context**
Still a great app :)

**Comment by mrfatboy** [comment]
Yes. Landscape viewing is now broken on my iPhone 11. I didn’t bother updating and test on my iPad 4.

**Comment by tylerjonesio** [comment]
Thanks for flagging this! It looks like there was a conflict with the new iPad enhancements and larger (plus sized) phones in landscape mode (due to the iPad like split view like layout). This should be fixed in version 2.3.1 which is currently in the process of rolling out. If you have any other issues with it, just let me know.

**Comment by mrfatboy** [comment]
Verified. It’s now working👍

**Comment by IchSchreiGleich** [comment]
Fixed. Issue can be closed.
