### ISSUE TITLE
Dlink DCS-2630L wont show video, but can see website.

### ISSUE THREAD

**Issue by rubernck21** [IPCams/BugTracker#51]
I've looked over my settings for my camera and I believe that everything is setup right, I've tried multiple variations of settings for the Type and Scheme.  My camera seems to be able to do RTSP, but using either the individual settings or the path feature don't seem to work. I've even tried using the http auth section and tried putting the pw into the RTSP path, but no good.

One time I had the Type set to Web Page and I can see the page, but nothing else.

**Comment by tylerjonesio** [comment]
Sorry about the issues you've encountered! I know there are some rough edges when it comes to setup for up cameras, and it is on my radar to work on (#39). In the mean time though, I'd love to help you get connected if at all possible!

It's promising that you can at least access the web page, that helps rule out a lot of issues. According to what I found online, it looks like your camera might support both an rtsp and mjpeg stream with the following settings shown below. Not sure if either of these is what you've tried, but if not feel free to try it out and let me how if it works. 

Otherwise If it still doesn't work, let me know what error(s) you get and which platform & app version you are using. With that I can hopefully dig deeper and see if there are any other issues at play.

| RTSP | MJPEG |
|-|-|
| Type: `RTSP` | Type: `MJPEG` |
| URL Scheme: `rtsp://` | URL Scheme: `http://` |
| Host/IP: (Your camera's IP address) | Host/IP: (Your camera's IP address)
| Port: `554` | Port: `80` |
| Path: `play1.sdp` (or play2.sdp) | Path: `video/mjpg.cgi` |
| ![IMG_0233](https://user-images.githubusercontent.com/8380082/115100087-98a51b00-9ef7-11eb-8428-21da73170543.PNG) | ![IMG_0234](https://user-images.githubusercontent.com/8380082/115100090-9e026580-9ef7-11eb-9e85-518f6d0dae88.PNG) |

_Note: In terms of authentication, if you enter your user and password into the designated http auth fields it will go ahead and build the url with them as required by most cameras. (i.e. `rtsp://username:password@192.168.0.100/play1.sdp`)._

**Comment by rubernck21** [comment]
Thank you for the response. As soon as I get back to my laptop, I’ll try these settings.


[https://i.imgur.com/slbgCTwt.jpg]
Alex Smith
[https://68ef2f69c7787d4078ac-7864ae55ba174c40683f10ab811d9167.ssl.cf1.rackcdn.com/facebook-icon_32x32.png]<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FDJSynnister&data=02%7C01%7C%7C0c46af3cb1a341d2c7c708d690684afb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636855174932841306&sdata=kuOGAhSAVVlk2sxt6PSh4%2F7wMfzsDcqu5bmiiUjLOok%3D&reserved=0>      [https://68ef2f69c7787d4078ac-7864ae55ba174c40683f10ab811d9167.ssl.cf1.rackcdn.com/twitter-icon_32x32.png] <https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2Frubernck21&data=02%7C01%7C%7C0c46af3cb1a341d2c7c708d690684afb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636855174932851311&sdata=njzo4qRhvvC4GyGGiZbONoivNOnSojr1vtA8%2F5AS22I%3D&reserved=0>    [https://68ef2f69c7787d4078ac-7864ae55ba174c40683f10ab811d9167.ssl.cf1.rackcdn.com/linkedin-icon_32x32.png] <https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Falexanderrsmith&data=02%7C01%7C%7C0c46af3cb1a341d2c7c708d690684afb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636855174932861328&sdata=w%2BzDpioZ%2BfBf%2Bs0AdToyJtzomSIH5RfYAUhLy6%2Bdl0c%3D&reserved=0>      [https://68ef2f69c7787d4078ac-7864ae55ba174c40683f10ab811d9167.ssl.cf1.rackcdn.com/youtube-icon_32x32.png] <https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fchannel%2FUCpUieUYDq9WFjITlGU8Zilg&data=02%7C01%7C%7C0c46af3cb1a341d2c7c708d690684afb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636855174932871333&sdata=pLOQixbctP1A3bHt0IweZSIp2P1KPd2GdbGdPE23UHo%3D&reserved=0>  [https://68ef2f69c7787d4078ac-7864ae55ba174c40683f10ab811d9167.ssl.cf1.rackcdn.com/skype-icon_32x32.png]
Cell: (913) 396-3111<tel:(913)396-3111> | Email: ***@***.******@***.***>

On Apr 16, 2021, at 10:23 PM, Tyler Jones ***@***.***> wrote:

﻿

Sorry about the issues you've encountered! I know there are some rough edges when it comes to setup for up cameras, and it is on my radar to work on (#39<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FIPCams%2FBugTracker%2Fissues%2F39&data=04%7C01%7C%7C9abecf23e9fc46fd9b9208d9015036f2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637542266290418979%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=b2KGGcV%2FIInfXuUVGgBVM%2F4lJfjVA20TAkMbvgjzHeE%3D&reserved=0>). In the mean time though, I'd love to help you get connected if at all possible!

It's promising that you can at least access the web page, that helps rule out a lot of issues. According to what I found online, it looks like your camera might support both an rtsp and mjpeg stream with the following settings shown below. Not sure if either of these is what you've tried, but if not feel free to try it out and let me how if it works.

Otherwise If it still doesn't work, let me know what error(s) you get and which platform & app version you are using. With that I can hopefully dig deeper and see if there are any other issues at play.

RTSP    MJPEG
Type: RTSP      Type: MJPEG
URL Scheme: rtsp://     URL Scheme: http://
Host/IP: (Your camera's IP address)     Host/IP: (Your camera's IP address)
Port: 554       Port: 80
Path: play1.sdp (or play2.sdp)  Path: video/mjpg.cgi
[IMG_0233]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F8380082%2F115100087-98a51b00-9ef7-11eb-8428-21da73170543.PNG&data=04%7C01%7C%7C9abecf23e9fc46fd9b9208d9015036f2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637542266290418979%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gqoxFHTBidzy1%2FP0PNmpXXYLQukySV5%2FuccbpStphWc%3D&reserved=0>  [IMG_0234] <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F8380082%2F115100090-9e026580-9ef7-11eb-9e85-518f6d0dae88.PNG&data=04%7C01%7C%7C9abecf23e9fc46fd9b9208d9015036f2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637542266290428939%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8Ou3nWrnVc0Xb02xztchGuHwqub2v2GES2f2vC051Xc%3D&reserved=0>

Note: In terms of authentication, if you enter your user and password into the designated http auth fields it will go ahead and build the url with them as required by most cameras. (i.e. ***@***.***/play1.sdp).

**Comment by rubernck21** [comment]
Didnt try the RTSP, but the mjpg worked flawlessly.  Is RTSP better than the other, or are they just about the same?

[https://i.imgur.com/slbgCTwt.jpg]
Alex Smith
[https://68ef2f69c7787d4078ac-7864ae55ba174c40683f10ab811d9167.ssl.cf1.rackcdn.com/facebook-icon_32x32.png]<https://www.facebook.com/DJSynnister>       [https://68ef2f69c7787d4078ac-7864ae55ba174c40683f10ab811d9167.ssl.cf1.rackcdn.com/twitter-icon_32x32.png] <https://twitter.com/rubernck21>     [https://68ef2f69c7787d4078ac-7864ae55ba174c40683f10ab811d9167.ssl.cf1.rackcdn.com/linkedin-icon_32x32.png] <https://www.linkedin.com/in/alexanderrsmith>       [https://68ef2f69c7787d4078ac-7864ae55ba174c40683f10ab811d9167.ssl.cf1.rackcdn.com/youtube-icon_32x32.png] <https://www.youtube.com/channel/UCpUieUYDq9WFjITlGU8Zilg>   [https://68ef2f69c7787d4078ac-7864ae55ba174c40683f10ab811d9167.ssl.cf1.rackcdn.com/skype-icon_32x32.png]
Cell: (913) 396-3111<tel:(913)396-3111> | Email: ***@***.******@***.***>

________________________________

**Comment by tylerjonesio** [comment]
I'm glad to hear it is working for you!

It's a little bit of give and take between MJPEG and RTSP streams. MJPEG is an older (simpler) stream type and lacks a lot of modern features, but can sometimes be more reliable and faster to load because of that. RTSP is a newer stream type that is more efficient, has more bells and whistles but takes more to decode. It is really up to the camera itself on what stream it implements, and how well it works.
